### ISSUE TITLE
Installing decidim-module-navbar error

### ISSUE THREAD

**Issue by gianluca326** [OpenSourcePolitics/decidim-module-navbar_links#1]
Hi,
i have this error :

There was an error parsing `Gemfile`: You cannot specify the same gem twice coming from different sources.
You specified that decidim-navbar_links (>= 0) should come from source at `.` and 
. Bundler cannot continue.

 #  from /home/ubuntu/decidim_application/Gemfile:29
 #  -------------------------------------------
 #    gem "spring", "~> 2.0"
 >    gem "decidim-navbar_links"
 #    gem "spring-watcher-listen", "~> 2.0"

Per quanto riguarda questo errore abbiamo controllato che la gem decidim navbar-links fosse inserita una singola volta nel GemFile

Una volta fatto questo abbiamo rifatto il procedimento descritto su GitHub ma esce questo errore

ubuntu@ubuntu-virtual-machine:~$ bundle
Traceback (most recent call last):
	2: from /home/ubuntu/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
	1: from /home/ubuntu/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/ubuntu/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

**Comment by armandfardeau** [comment]
Hi, and thanks for your issue, it helps this module to improve.

Would you mind formatting your message a bit and translate the Italian part in English, it will ensure a better understanding and communication.

Regarding your issue, I've tested on a 0.18 release and I'm doing an update on 0.19.1.

May you provide 
- [ ] a complete stack trace of your error(s)
- [ ] your bundler version

**Comment by gianluca326** [comment]
Thank you!
This is the error :

There was an error parsing `Gemfile`: You cannot specify the same gem twice coming from different sources.
You specified that decidim-navbar_links (>= 0) should come from source at `.` and 
. Bundler cannot continue.

 #  from /home/ubuntu/decidim_application/Gemfile:29
 #  -------------------------------------------
 #    gem "spring", "~> 2.0"
 >    gem "decidim-navbar_links"
 #    gem "spring-watcher-listen", "~> 2.0"

Regarding this error, we checked that the gem decidim navbar-links was inserted once in the GemFile
Once we did this we redone the procedure described on GitHub but this error comes out :

ubuntu@ubuntu-virtual-machine:~$ bundle
Traceback (most recent call last):
	2: from /home/ubuntu/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
	1: from /home/ubuntu/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/ubuntu/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

**Comment by armandfardeau** [comment]
Hi, 

May you give me the output of the following command: 
`bundler -v`

It looks like a problem coming from your installation. Not from this module.
https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html

**Comment by gianluca326** [comment]
Bundler version 2.1.2

**Comment by armandfardeau** [comment]
Maybe you can use the same version of bundler as this module:

`gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)`
